[package]
name = "http"
version = "0.0.1"
authors = ["dan sinclair <dj2@everburning.com>"]
edition = "2018"
description = "http processing helpers"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/dj2/Archive/server"
